---
title: "La lógica como disciplina"
---

Cuando entran en la carrera de abogacía lo que la mayoría piensa es que no van a ver nada relacionado con las matemáticas.
Sin embargo, como veremos dentro de poco, para poder razonar correctamente se necesita algo de estructura.
Se necesita poder ordenar los "pensamientos" de uno para expresarlos de la mejor manera posible.
Para que los otros puedan escuchar y entenderlos lo más claro posible.

Realizamos razonamientos todo el tiempo.
Muchos de ellos sin darnos cuenta.
[TODO: Pensar ideas de razonamientos cotidianos]
Discutimos y debatimos con varias personas que nos encontramos todos los días,
queramos o no.
Tomamos decisiones basándonos en razones, incluso incluyendo a las emociones
como razones mismas para sostener nuestra tesis.

Por todo esto es necesario tener algunos conocimientos de lógica.
Les aseguramos que, si estudian a conciencia,
la lógica les va a permitir estructurar mejor sus razonamientos,
encontrar sus propios errores y en los demás,
contribuir de mejor manera a la discusión
y sobre todo, pensar de mejor manera.

La lógica, como fue pensada desde sus inicios
^[Quien fundó la lógica como una disciplina sistematizada fue Aristóteles.
Esto no quiere decir que antes de él no se usaba lógica o los seres humanos no hacían cosas lógicas.
Por supuesto que si, pero fue él quien pudo sistematizar en varios obras parte de lo que veremos en la materia.],
fue considerada como un *organon*, como una herramienta.

Esa herramienta la usamos para hacer mejores razonamientos.
Ahora bien, ¿qué es un razonamiento?
Antes de poder responder la pregunta hay que aclarar la perspectiva, la postura
desde la cual la lógica va a considerar a la lógica.
La lógica es una disciplina formal.
Esto quiere decir que el punto central para la lógica son las *formas de los razonamientos*,
es decir la estructura última de los razonamientos.
A diferencia de otras ciencias a la lógica no le interesa un objeto particular de estudio
(como ser la vida para la biología, la tierra para la geología o la interacción de entidades materiales para la física)
solo le interesa las relaciones formales que usamos, hacemos al momento de realizar razonamientos.

Lógicamente hablando un razonamiento es lo siguiente:

> Una secuencia de proposiciones las cuales un grupo de ellas serán denominadas *premisas*
> y otra proposición denominada *conclusión* que puede derivarse del primer grupo.

Explicitado formalmente:

> $P_{1}, P_{2}, ... , P_{1} \Rightarrow C$

Donde las $P$ serán las premisas, la $C$ es la conclusión
y el signo "$\Rightarrow$" es la denominada *relación de consecuencia lógica*
^[El signo de la flecha en otros libros aparece como $\vdash, \models, \rightarrow$.
Si bien cada uno de los signos tiene sus diferencias conceptuales, la idea general se sostiene.
Todos indican una relación de consecuencia lógica.]
que da cuenta de la relación entre las premisas y la conclusión.

La lógica va a indagar como de un conjunto de premisas cualquiera se llega a un conclusión.
En particular se va a interesar por los razonamientos denominado *válidos*.
^[A qué llamamos razonamiento válido lo veremos más adelante.]

Como se puede observar, el razonamiento al ser una cadena de enunciados,
esta se tiene que expresar gracias al lenguaje.
Sea escrito u oral.
Nuestras ideas y pensamientos siempre se tienen que expresar en base al lenguaje
para poder ser comunicadas a resto.

## La semiótica

Por más que la lógica sea una disciplina formal,
tiene que tener alguna noción de cómo analizar el lenguaje.
Para ello va a nutrirse de la teoría de los signos,
ya que todo aquello que digamos, escribamos, o expresemos
puede ser considerado como un signo.
La teoría de los signos, o también denominada semiótica
se divide en tres subareas.
Estas áreas se caracterizan por hacer foco en cierta dimensión del lenguaje.
Éstas son:

1. La sintaxis
2. La semántica
3. La Pragmática

La primera hace referencia a la relación que tienen los signos entre sí.
Recuerden cuando en la escuela secundaria se ejercitaba el análisis sintáctico de las oraciones.
Lo que se hacía en dicho análisis era ver como cada una de las palabras de la oración se encontraba relacionada con las otras.
Como la oración tenía un sujeto, un predicado un verbo, entre otros elementos sintácticos.
El análisis sintáctico de oraciones es solo un ejemplo de lo que comprende la sintaxis dentro de la semiótica.

La segunda hace referencia a la relación que tienen el signo con aquello a lo cual refiere.
La relación entre el signo y la realidad.
Por ejemplo, enunciar lo siguiente:

> "El gato del profesor Gavriloff se llama simba" es verdadero

Nos habla de una relación semántica debido a que esta diciendo que la oración
"El gato del profesor Gavriloff se llama Simba" porta verdad, es verdadera
puesto que de hecho es así en la realidad
(el gato del profesor Gavriloff si se llama Simba,
uno lo llama por ese nombre y responde)
es que podemos decir que es verdadera.
Todo este ejemplo es un ejemplo de un análisis semántico,
un análisis acerca de la relación entre lo que se dice con como es el mundo.

La tercera área es la pragmática.
Aquí se va a estudiar la relación de cómo se hace uso de los signos.
Ni siquiera en cómo es la relación con las cosas en sí mismas,
sino en como los agentes hacen uso de los signos.
Un ejemplo típico de análisis pragmático es considerar al semáforo y lo que indican sus colores:
los colores rojo, amarillo y verde no dicen nada acerca de lo que tenemos que hacer en la calle cuando lo vemos
pero en un semáforo todos los peatones y conductores entienden que cuando está en rojo
esto significa que los vehículos no pueden avanzar,
y que los peatones pueden cruzar la calle;
cuando está en amarillo indica que hay que tener precaución al conducir
y cuando está en verde significa que los vehículos pueden avanzar
y los peatones tienen que esperar hasta que el semáforo esté en rojo para poder cruzar la calle.

Esto es muy necesario como pre requisito para estudiar apropiadamente lógica.
Incluso algunos lógicos han indicado que la lógica puede ser considera una disciplina de la semiótica.
Aunque no indagaremos esto por el momento.
Lo que es necesario de todo esto es que la lógica trabaja con el lenguaje.
Como tiene como objeto de estudio a los razonamientos,
tiene que tener ciertas nociones de las disciplinas sobre el lenguaje como base
para poder llevar a cabo un mejor análisis.

Ahora bien, las premisas y las conclusiones son proposiciones.
A primer visto uno puede denominarlas oraciones,
pero el problema con ello es que el concepto de oración se encuentra asociado a la lengua,
no a la lógica.
Los lógicos han usado el término proposición para referirse a las premisas y a la conclusión de los razonamientos.

Teniendo en cuenta las siguientes oraciones:

> "El gato está sobre la mesa"
>
> "The cat is on the table"
>
> "Die Katze ist auf dem Tisch"

Todas tienen la misma proposición $p$ "El gato está sobre la mesa".
Es decir, una proposición es un enunciado completo que tiene la característica de poder ser verdadero o falso.
Es un enunciado que es portador de verdad.

::: {.callout-important title="Definición"}
Una proposición es un enunciado descriptivo completo el cual es capaz de ser verdadero o falso.
:::

Como se puede observar las oraciones del ejemplo están en distintos idiomas:
español, ingles y alemán respectivamente,
pero todas comparten la misma proposición.
Si supiésemos los tres idiomas sabríamos que dicen lo mismo,
eso común que tienen estas oraciones es el *contenido proposicional*.
La proposición tiene que ser un enunciado completo,
es decir debe constar de todos los elementos básicos de una oración que tiene sentido.
No podemos considerar una proposición que solo sea un nombre como "Pedro"
o una oración incompleta como "Juan iba".
Tiene que tener sentido por sí misma,
sino no puede extraerse ni formalizarse su contenido proposicional.

::: {.callout-warning title="Diferencias a tener en cuenta"}
Esto es importante porque como veremos a lo largo de todo el cursado,
el análisis lógico es distinto al análisis gramatical o de lengua
que hemos estudiado en la escuela.
:::

En la nota más arriba, hemos dicho que la proposición es descriptiva,
esto es así debido a que los enunciados de las proposiciones dan cuenta del mundo,
por ello es que pueden ser verdaderos o falsos.
El lenguaje tiene muchas funciones.
Es gracias a esto que podemos realizar muchas acciones en el mundo.
Algunas de las funciones del lenguaje son:

* Descriptiva
* Cuestionar
* Comandar

Nosotros nos concentraremos en la descriptiva.
Solo vamos a formalizar y a concentrarnos en aquellos enunciados que cumplen una función descriptiva.
¿Que hacemos con los otros enunciados?
Por el momento no les prestaremos atención ni intentaremos formalizarlos.
Esto se debe que, por ejemplo, ni las preguntas ni las ordenes pueden tener algún valor de verdad,
no son ni verdaderas ni falsas.

## Sistema de lógica proposicional

Con los conocmientos preliminares ya cubiertos,
es necesario pasar a presentar al sistema lógico que vamos a usar durante la materia.

El nombre del sistema es el de Lógica proposicional o cálculo de lógica proposicional.

El sistema consta de varios elementos que vamos a explicar uno por uno.

El sistema consta de dos grandes grupos: las variables lógicas y las constantes o conectivas lógicas.

### Variables lógicas

Las variables lógicas son las denominadas variables proposicionales.
Son aquellos signos que nos permiten poder formalizar cualquier enunciado.
Comúnmente los lógicos utilizan letras minúsculas que van desde la p en adelante
(en orden alfabético): $p, q, r, s, t, ...$.

### Constantes o conectivas lógicas

El segundo grupo a considerar son las constantes o conectivas lógicas.
Denominadas así porque su significado no cambian
(en contraposición a las variables, que *varían* su contenido).
También son llamadas conectivas porque la mayoría de ellas conectan dos o más proposiciones.

Las conectivas pueden clasificarse en dos grupos:

1. **Monádicas**: Son aquellas que solo afectan a una proposición.
   * Este es el caso de la negación. 
     La negación es la partícula del lenguaje que nosotros usamos como:
     "No"; "no es cierto que...": "No es verdad que...".
   * Sus símbolos pueden ser $\neg$ o $\sim$
   * **Ejemplo:** $\neg p$ o $\sim p$
2. **Diádicas**: Son aquellas que afectan al menos dos proposiciones.
    * **Conjunción**: Corresponde a la partícula "y"; "pero"; "aunque".
      Sus símbolos son: $\land$ o $\bullet$. Ejemplo: $p \land q$
    * **Disyunción**: Corresponde a la partícula "o"; "o bien... o bien...".
      Su símbolo es: $\lor$. Ejemplo: $p \lor q$
    * **Condicional**: Corresponde a las partículas "Si..., entonces..."
      Sus símbolos son: $\rightarrow$; $\supset$. Ejemplo: $p \supset q$
    * **Bicondicional**: Corresponde a las partículas "si y solo si..."
      sus símbolos son: $\rightleftarrows$ o $\equiv$. Ejemplo: $p \equiv q$

### Símbolos auxiliares

Por último tenemos los símbolos auxiliares que nos servirán para poder delimitar alcances de las proposiciones.
Estos son las llaves, los corchetes y los paréntesis: $(\ ); [\ ]; \{\ \}$.
Estos nos permiten realizar ciertas delimitaciones importantes a la hora de entender lo que cada fórmula o proposición afirma.
Por ejemplo no es lo mismo $(p \supset q) \land p$ que $p \supset q \land p$.
En el segundo caso no podemos saber a ciencia cierta si el condicional afecta solo a $q$ o también a la conjunción con $p$.
La importancia de estos signos se va a ver mejor cuando se realicen los ejercicios de simbolización.

## Conclusión

De esta manera hemos introducido los conceptos básicos de lo que es la lógica,
su objeto de estudio, las nociones necesarias para poder comprender cuál es la finalidad e la lógica,
y hemos presentado brevemente el sistema de lógica proposicional.
En la siguiente unidad vamos a introducirnos más en el cáculo proposicional y en su utilidad.
