---
title: Lógica Proposicional
---

## Introducción

Como habíamos visto en la unidad anterior vamos a trabajar con un sistema lógico en particular.
El sistema de la lógica proposicional.

Ya lo habíamos caracterizado también.
El sistema consta de:

1. Variables proposicional, las cuales servirán para formalizar cada una de las proposiciones.
   Ejemplo: $p, q, r, ...$
2. Constantes o conectivas proposicionales: las cuales servirán para formalizar
   las particular que realizan uniones o modifican a las proposiciones.
   Estas eran:
    * La negación ($\neg, \sim$).
    * La conjunción ($\land, \bullet$).
    * La disyunción ($\lor$).
    * El condicional ($\supset, \rightarrow$).
    * El bicondicional ($\equiv, \leftrightarrow$).
3. Los símbolos auxiliares, los cuales sirven para delimitar el alcance de las conectivas.
   Entre ellos encontramos a los paréntesis ($( \ )$), los corchetes ($[ \ ]$) y las llaves ($\{ \ \}$).

Estos son los elementos que necesitamos para la poder llevar a cabo la formalización.

Antes de poder llevar a ver cómo analizamos los razonamientos,
es primordial tener conocimiento y entrenamiento en cómo formalizar las proposiciones.
Recordemos que lo que se trata es de pasar de lo que decimos en lenguaje natural
-en nuestro caso el castellano-
a un lenguaje formalizado
-en este caso la lógica proposicional-.

Recordemos la noción de proposición:

> Un enunciado completo descriptivo con la capacidad de ser verdadero o falso.

Entonces cuando nos embarquemos en la tarea de formalizar proposiciones,
tenemos que tener en cuenta su definición,
puesto que en ella se encuentran las características que nos dirán cómo tenemos que formalizar.

Además es importante tener en cuenta también las apariciones de las partículas
que hacen referencia a las conectivas lógicas.
Así como los signos de puntuación nos indican donde empieza y termina una oración,
o como tiene que ser el énfasis y las pausas de la misma,
las conectivas también nos pueden indicar donde empieza y termina una proposición
y cómo es que se unen unas con otras.
^[Incluso algunos lógicos las consideran *como* signos de puntuación.
Es decir, van más allá de la analogía aquí propuesta.
Esto es un tema de filosofía de la lógica,
no es necesario indagar esto en un curso introductorio de lógico como el presente.]

## Simbolización

Para poder pasar del lenguaje ordinario al lenguaje formal,
es necesario tener un entrenamiento que sea capaz de
adquirir las habilidades para identificar cada uno de los elementos formales
en el lenguaje ordinario.
Es decir, poder leer cualquier oración
y poder indicar qué parte de la oración es una proposición,
una conectiva lógica
y donde poner los símbolos auxiliares para
que la formula en lógica proposicional tenga el mismo sentido que en lenguaje ordinario.

Aquí vamos a colocar algunos ejemplos básicos para que puedan entender,
y luego se irá acompleja cada vez más.

:::{.callout-note title="Sobre los ejercicios"}
En el sitio web se encuentran en una solapa separada todos los ejercicios de las unidades.

Ir al [link]()
<!-- TODO: Agregar link de los ejericios -->
:::

Primero que nada vamos a ver algunos ejemplos de simbolizaciones básicas:

**Dadas los siguientes enunciados simbolice usando la el sistema de lógica proposicional:**

1. Juan trabaja todos los días.
1. María y Diego están de vacaciones.
1. El agua hierve a una temperatura de 100°C al nivel del mar

**Resolución:**

1. En el primero vemos que solo tenemos una proposición debido a que el enunciado es completo 
   y es un enunciado descriptivo por lo que simplemente lo simbolizamos:
   $$p$$
1. En el segundo caso vemos que tenemos dos sujetos: Maria *y* Diego.
   Por lo que tenemos que ver qué es lo que están haciendo cada uno de ello.
   María está de vacaciones. Diego está de vacaciones también.
   Si bien los dos se encuentran en el mismo estado, son dos sujetos distintos.
   Por lo que para la lógica proposicional son dos proposiciones distintas:
   $p$ para Maria y $q$ para Diego.
   Cuando analizamos un enunciado que, a primera vista, parece una sola proposición pero no lo es,
   la recomendación es armar un *diccionario*.
   Esto quiere decir indicar cual es la referencia de cada una de las proposiciones.
   * Para este ejercicio sería así:
     $$p: María\ está\ de\ vacaciones$$

     $$q: Diego\ está\ de\ vacaciones$$

     $$p \bullet q$$
   * Como pueden ver aquí hemos introducido una conectiva lógica,
     la conjunción entre las dos proposiciones.
     Así se realiza una unión entre las proposiciones.
1. En el tercer caso, por más que parezca un enunciado bastante largo y de cierta complejidad es solo una proposición.
   * Por lo que su simbolización es la siguiente: $$p$$

Como hemos dicho más arriba estos son algunos ejemplos básicos,
pero ya nos llevan a que tengamos ciertas cuestiones a considerar.
Estas van a estar marcadas en el apartado en los *pro tips*:

::: {.callout-important title="Pro tips"}
* Verificar si el enunciado que se desea formalizar es un enunciado descriptivo capaz de ser verdadero o falso.
* Siempre hacer diccionario a la hora de simbolizar.
  Ayuda a ordenar mejor las proposiciones y evitar confusiones.
* Ubicar las conectivas lógicas para encontrar donde puede haber más de una proposición.
:::

### Reglas de formación

Para poder realizar formalizaciones correctas todo sistema de lógica posee reglas
que cumplen la función de indicar cuándo y cómo las formulas del sistema se encuentran bien formadas.

La sintáxis del lenguaje natural también hace esto, por ejemplo:

"*Hoy vamos a tener clase de lógica*" es una oración bien formulada. Todos la podemos entender.

"*De Vamos a hoy*" por ejemplo no se encuentra bien formulada, no puede entender lo que dice.

En este sentido en lógica proposicional, por ejemplo:

$$p \bullet q$$ es una fórmula bien formada (fbf) mientras que $$\bullet q p$$ no lo es.

Las reglas de formación de la lógica proposicional son las siguientes:

1. Si $\alpha$
   ^[Utilizamos $\alpha$ y $\beta$ para varible meta-logicas.
   Estas variables comprenden desde una simple proposición cualquiera como $p$
   hasta propociones de cualquier complejidad como por ejemplo $(p \lor t) \supset [q \supset (r \bullet s)]$]
   es una fbf, entonces $\sim \alpha$ también es una fbf.
1. Si $\alpha$ y $\beta$ es una fbf, entonces $\alpha \lor \beta$ es una fbf.
1. No hay más fbf.

Como pueden ver las reglas de formación solo hacen uso de la negación y de la disyunción.
Esto se debe a que todas las demás conectivas lógicas pueden definirse en base a la negación y disyunción.
La negación y la disyunción son denominadas como *terminos primitivos*,
es decir no se pueden definir por ninguna otra conectiva.

Por otro lado, la tercera regla indica una *cancelación* o *clausura* de todo tipo de regla de formación.
Solo y solo esas reglas son las necesarias y suficientes para poder formalizar cualquier fórmula.

Como puede verse las reglas de formación también indican el orden en que las conectivas deben ser escritas.
La negación va antes de cualquier proposición y las demás conectivas diádicas van entre dos proposiciones.

# Presentación de clase

::: slide-deck

:::
